### ISSUE TITLE
could you display a demo or some explanation?

### ISSUE THREAD

**Issue by zdiovo** [EPICAPPSLTD/EPICEncryption#1]
could you display a demo or some explanation?  thanks.

**Comment by EPICAPPSLTD** [comment]
It's on my TODO list. Will take care of documenting this properly in the next following days.

**Comment by EPICAPPSLTD** [comment]
I've extended the explanation on the readme file. Usage should now be clear for anybody wanting to use this library. I'm considering the issue closed.
